# Script Name: clearlogs
# Purpose:     Clears all log files and crash reports generated by the program.
# Usage:       .\clearlogs.ps1
# Author:      SlavSquatSuperstar

# Get the original calling directory
$Location = (Get-Location).Path

# Navigate to the project directory
$SCRIPT_DIR = $PSSCRIPTROOT
Set-Location "$SCRIPT_DIR"
if (-not$?)
{
    exit
}

# Delete log outputs and crash reports
Get-ChildItem -Recurse -Directory -Filter "logs" | Remove-Item -Recurse
Get-ChildItem -Recurse -File -Filter "hs_err_pid*.log" | Remove-Item
Write-Output "Cleared all log files."

# Exit and navigate to the previous directory
Set-Location $Location
exit 0
