#!/bin/sh
# Navigate to the project directory
SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR" || exit

# Delete log folder outputs
rm -r logs/
rm -r mayonez-base/logs/
rm hs_err_pid*.log
echo "Cleared all log files"