@echo off

rem Script Name: clearlogs.bat
rem Purpose:     Clears all log files and crash reports generated by the program.
rem Usage:       .\clearlogs.bat
rem Author:      SlavSquatSuperstar

rem Navigate to the project directory
set SCRIPT_DIR=%~dp0
cd %SCRIPT_DIR% || exit /b 1

rem Delete log folder outputs
rmdir /s /q logs\ mayonez-demos\logs\
del hs_err_pid*.log mayonez-demos\hs_err_pid*.log
echo Cleared all log files.