@echo off

rem Script Name: clearlogs.bat
rem Purpose:     Clears all log files and crash reports generated by the program.
rem Usage:       .\clearlogs.bat
rem Author:      SlavSquatSuperstar

rem Navigate to the project directory
set SCRIPT_DIR=%~dp0
cd %SCRIPT_DIR% || exit /b 1

rem Delete log folder outputs
rmdir /S /Q logs\ || echo "No log files to delete."
rmdir /S /Q dist\logs\ || echo "No log files to delete in dist."
del hs_err_pid*.log || echo "No crash reports to delete."
echo Cleared all log files.