#!/bin/sh

# Script Name: clearlogs.sh
# Purpose:     Clears all log files and crash reports generated by the program.
# Usage:       ./clearlogs.sh
# Author:      SlavSquatSuperstar

# Navigate to the project directory
SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR" || exit

# Delete log outputs and crash reports
find . -type d -name "logs" -exec rm -r {} +
find . -type f -name "hs_err_pid*.log" -exec rm {} +
echo "Cleared all log files."
