#!/bin/sh

# Script Name: package
# Purpose:     Packages the Mayonez Engine program for release on GitHub.
# Usage:       ./package
# Author:      SlavSquatSuperstar

# Navigate to the project directory
SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR" || exit

# Build the Gradle project
echo "Building Mayonez Engine..."
if [ "$(./gradlew clean shadowJar)" ]; then
  echo "Successfully built Mayonez Engine."
else
  echo "Error building Mayonez Engine."
  exit 1
fi

# Copy the compiled .jar file
cp build/libs/mayonez*.jar dist/

# Copy the license file
cp LICENSE-GPLv3.txt dist/LICENSE.txt

# Show success message
echo "Successfully packaged Mayonez Engine."