#!/bin/sh

# Script Name: package
# Purpose:     Packages the Mayonez Engine program for release on GitHub.
# Usage:       ./package
# Author:      SlavSquatSuperstar

# Navigate to the project directory
SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR" || exit

# Build the Gradle project
echo "Building Mayonez Engine..."
if [ "$(./gradlew jar)" ]; then
  echo "Successfully built Mayonez Engine."
else
  echo "Error building Mayonez Engine."
  exit 1
fi

# Replace the compiled .jar file
rm dist/mayonez*.jar
cp mayonez-demos/build/libs/mayonez*.jar dist/

# Copy resource files
cp LICENSE.txt dist/
cp release-assets/resources/* dist/
cp release-assets/scripts/* dist/

# Zip the dist folder
cd dist || exit
rm mayonez*.zip
zip mayonez-engine.zip -- mayonez*.jar run* *.json *.txt

# Show success message
echo "Successfully packaged Mayonez Engine."
