#!/bin/sh

# Navigate to the project directory
SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR" || exit

# Read arguments
if [[ "$1" = "false"* ]]; then
  USE_GL=false
else
  USE_GL=true
fi

# Check operating system
MAC_OS=false

if [[ "$OSTYPE" = "linux-gnu"* ]]; then
  echo "Detecting GNU/Linux."
elif [[ "$OSTYPE" = "darwin"* ]]; then
  echo "Detecting macOS."
  MAC_OS=true
elif [[ "$OSTYPE" = "cygwin"* || "$OSTYPE" = "mingw"* || "$OSTYPE" = *"msys" ]]; then
  echo "Detecting Windows."
  echo "Please use 'run.bat' insead."
  exit 1
else
  echo "Unknown operating system detected."
fi

# Check if Java is installed
if [ "$(java --version)" ]; then
  echo "Java is installed."
else
  echo "Please install Java."
  exit 1
fi

# Build the application for Unix systems (macOS/Linux)
echo "Building Mayonez Engine..."
if [ "$(./gradlew clean build)" ]; then
  echo "Successfully built Mayonez Engine."
else
  echo "Error building Mayonez Engine."
  exit 1
fi

# Run the compiled .jar file
if $USE_GL; then
  echo "Launching with OpenGL Engine."

  if $MAC_OS; then
    # LWJGL requires a special argument on macOS
    java -XstartOnFirstThread -jar build/libs/*.jar "$USE_GL"
  else
    java -jar build/libs/*.jar "$USE_GL"
  fi
else
  echo "Launching with AWT Engine."
  java -jar build/libs/*.jar "$USE_GL"
fi
