package slavsquatsuperstar.demos.spacegame.objects.asteroids;

import mayonez.math.*;

/**
 * An asteroid randomly generated by a spawner.
 *
 * @author SlavSquatSuperstar
 */
public class RandomAsteroid extends Asteroid {

    public RandomAsteroid(String name, Vec2 position, AsteroidProperties properties) {
        super(name, position, properties);
    }

    @Override
    protected void init() {
        super.init();
        var startingHealth = properties.getHealth();
        addRigidbody(startingHealth)
                .setVelocity(transform.getUp().mul(Random.randomFloat(0f, 3f)));

        // Create more fragments
        addComponent(new AsteroidDestruction(startingHealth, properties));
        addCollider();
    }

}
