package slavsquatsuperstar.demos.spacegame.objects.asteroids;

import mayonez.graphics.*;
import mayonez.math.*;

/**
 * An asteroid randomly generated by a spawner.
 *
 * @author SlavSquatSuperstar
 */
public class RandomAsteroid extends Asteroid {

    private static final float MIN_RADIUS = 1f;
    private static final float MAX_RADIUS = 4f;

    public RandomAsteroid(String name, Vec2 position) {
        super(name, position, getRandomProperties());
    }

    @Override
    protected void init() {
        super.init();
        var startingHealth = properties.getHealth();
        addRigidbody(startingHealth)
                .setVelocity(transform.getUp().mul(Random.randomFloat(0f, 3f)));

        // Create more fragments
        var script = new AsteroidDestruction(startingHealth, properties);
        addComponent(script);
        addCollider(script);
    }

    private static AsteroidProperties getRandomProperties() {
        var radius = Random.randomFloat(MIN_RADIUS, MAX_RADIUS);
        var color = Color.grayscale(Random.randomInt(96, 176));
        return new AsteroidProperties(radius, color, Random.randomInt(0, Asteroid.NUM_TEXTURES - 1));
    }

}
